apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: truc-backstage
  annotations:
    github.com/project-slug: befabry/truc-backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests
